// <auto-generated />
using BotWalletWatcher;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExchangeLemonCore.Migrations.Block
{
    [DbContext(typeof(BlockContext))]
    partial class BlockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BotWalletWatcherLibrary.WatcherAddressItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("BlockChainId");

                    b.Property<bool>("IsSend");

                    b.HasKey("Id");

                    b.ToTable("WatcherAddresses");
                });

            modelBuilder.Entity("BotWalletWatcherLibrary.WatcherBlockChain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlockChainNumber");

                    b.Property<int>("Confirmations");

                    b.Property<bool>("IsFinish");

                    b.HasKey("Id");

                    b.ToTable("WatcherBlockChains");
                });

            modelBuilder.Entity("BotWalletWatcherLibrary.WatcherTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlockChainId");

                    b.Property<int>("Confirmations");

                    b.Property<bool>("IsSend");

                    b.Property<string>("TransactionId");

                    b.HasKey("Id");

                    b.ToTable("WatcherTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
