// <auto-generated />
using System;
using BlueLight.Main;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExchangeLemonCore.Migrations.LoggingExt
{
    [DbContext(typeof(LoggingExtContext))]
    [Migration("20180806041353_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlueLight.Main.LogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddtionalContent");

                    b.Property<string>("CallerName");

                    b.Property<string>("ClassName");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("Duration");

                    b.Property<string>("ModuleName");

                    b.Property<string>("SessionId");

                    b.Property<DateTime?>("StartBatchDate");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("LogItems");
                });
#pragma warning restore 612, 618
        }
    }
}
