// <auto-generated />
using System;
using BlueLight.Main;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExchangeLemonCore.Migrations.Logging
{
    [DbContext(typeof(LoggingContext))]
    [Migration("20180911070700_ReceiveLog")]
    partial class ReceiveLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogReceiveAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("EventType");

                    b.Property<Guid>("SessionId");

                    b.HasKey("Id");

                    b.ToTable("LogReceiveAddresses");
                });

            modelBuilder.Entity("LogReceiveAddressDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<int?>("LogReceiveAddressId");

                    b.HasKey("Id");

                    b.HasIndex("LogReceiveAddressId");

                    b.ToTable("LogReceiveAddressDetails");
                });

            modelBuilder.Entity("LogReceiveRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("EventType");

                    b.Property<Guid>("SessionId");

                    b.HasKey("Id");

                    b.ToTable("LogReceiveRaws");
                });

            modelBuilder.Entity("LogReceiveAddressDetail", b =>
                {
                    b.HasOne("LogReceiveAddress", "LogReceiveAddress")
                        .WithMany("Details")
                        .HasForeignKey("LogReceiveAddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
